[project]
name = "pantheondle"
version = "0.1.0"
description = "Play with Pantheon.world data and try to guess who is the famous person depicted"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nicegui>=3.15.0",
    "pandas>=2.3.3",
    "pandas-stubs>=3.0.5.260730",
    "pyarrow>=25.0.1",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pantheondle"]

[tool.pyright]
reportUnusedCallResult = false

[dependency-groups]
dev = [
    "deptry>=0.25.1",
    "ruff>=0.16.1",
]

[tool.deptry]
known_first_party = ["pantheondle"]
